on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-22.04
    outputs:
      release_created: steps.release.outputs.release_created
    steps:
      - uses: google-github-actions/release-please-action@a37ac6e4f6449ce8b3f7607e4d97d0146028dc0b # v.4.1.0
        id: release
        with:
          # a personal access token (PAT) for the release
          token: ${{ secrets.RELEASE_TOKEN }}
          release-type: node
      - name: release-created
        run: echo "Release created"
        if: ${{ steps.release.outputs.release_created }}

  npm-publish:
    needs: [release-please]
    if: ${{ needs.release-please.outputs.release_created }}
    runs-on: ubuntu-22.04
    steps:
      - run: echo "Release created"
#      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
#      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
#        with:
#          node-version: 20
#          registry-url: https://registry.npmjs.org/
#      - run: npm ci
#      - run: npm publish
#        env:
#          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
